spring:
  datasource:
    url: jdbc:oracle:thin:@10.202.239.112:1565:XTHO002T
    username: THOR_COMDATA
    password: THOR_COMDATA
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
      allow-pool-suspension: true
      register-mbeans: true
