spring:
  datasource:
    url: jdbc:oracle:thin:@ewfqgthrdo02.corp.awsedison.it:1521:THRQA
    username: THOR_COMDATA
    password: THOR_COMDATA
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
      allow-pool-suspension: true
      register-mbeans: true
