spring:
  datasource:
    url: jdbc:oracle:thin:@ewfqgthrdo01-import.ccaf44jvivwg.eu-central-1.rds.amazonaws.com:1521:THRQA
    username: THOR_COMDATA
    password: THOR_COMDATA
    driverClassName: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
      allow-pool-suspension: true
      register-mbeans: true
