apiVersion: apps/v1
kind: Deployment
metadata:
  name: intcomdata-deployment
  labels:
    app: thr-prod-comdata-tg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thr-prod-comdata-tg
  template:
    metadata:
      labels:
        app: thr-prod-comdata-tg
    spec:
      nodeSelector:
          function: THR-Application-Server
      serviceAccountName: thr-prod-sa
      securityContext:
        fsGroup: 9000
      containers:
      - name: intcomdata-prod
        image: 623333656140.dkr.ecr.eu-central-1.amazonaws.com/thor/intcomdata-prod:1.0.0-SNAPSHOT-20210520090557

        ports:
        - containerPort: 8443

        volumeMounts:
        - name: cert
          mountPath: "/etc/pki/tls/certs/internal/"
          readOnly: true

        env:
        - name: APP_ENV
          value: "prod"

        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "killall java"]

        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            scheme: HTTPS
            path: /actuator/health/liveness
            port: 8443

        readinessProbe:
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 30
          httpGet:
            scheme: HTTPS
            path: /actuator/health/readiness
            port: 8443

      volumes:
      - name: cert
        secret:
          secretName: thor-integrazioni.corp.awsedison.it
